// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgVq8byNQHx476ZOtj0LJ0DhGjvGvRPk',
    appId: '1:35956968707:web:eef0e99dd74d4211eaed36',
    messagingSenderId: '35956968707',
    projectId: 'neumarket-fd017',
    authDomain: 'neumarket-fd017.firebaseapp.com',
    storageBucket: 'neumarket-fd017.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOsVLJ4trbLoInSi0KgrPsr8X25H6zFC4',
    appId: '1:35956968707:android:c248e160670f23f2eaed36',
    messagingSenderId: '35956968707',
    projectId: 'neumarket-fd017',
    storageBucket: 'neumarket-fd017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-mwvtmLgxalVCZfSJG7DjUTj24ZPj8as',
    appId: '1:35956968707:ios:f887e8365c5ea34eeaed36',
    messagingSenderId: '35956968707',
    projectId: 'neumarket-fd017',
    storageBucket: 'neumarket-fd017.appspot.com',
    iosClientId: '35956968707-vha19t772c60qp60em568i4jvh2sjrhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-mwvtmLgxalVCZfSJG7DjUTj24ZPj8as',
    appId: '1:35956968707:ios:f887e8365c5ea34eeaed36',
    messagingSenderId: '35956968707',
    projectId: 'neumarket-fd017',
    storageBucket: 'neumarket-fd017.appspot.com',
    iosClientId: '35956968707-vha19t772c60qp60em568i4jvh2sjrhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
